server:
  port: 8083
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  application:
    name: employee_service
  datasource:
    url: jdbc:h2:mem:test
        